# Generated by Django 6.0.5 on 2026-05-22 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(db_index=True, max_length=24)),
                ('callsign', models.CharField(db_index=True, max_length=16)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('icao24', 'callsign')},
            },
        ),
        migrations.CreateModel(
            name='LandingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_time', models.DateTimeField(auto_now_add=True)),
                ('max_velocity', models.FloatField(help_text='Maximum recorded speed in m/s')),
                ('max_altitude', models.FloatField(help_text='Maximum recorded altitude in meters')),
                ('squawk_at_landing', models.CharField(blank=True, max_length=8, null=True)),
                ('flight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='core.flightlog')),
            ],
            options={
                'ordering': ['-landing_time'],
            },
        ),
    ]
